Fix undefined reference to GC_objfreelist and GC_bytes_allocd
This error happened only when `SEPARATE_GLOBALS` macro was defined.

* include/private/gc_priv.h [SEPARATE_GLOBALS] (GC_objfreelist,
GC_aobjfreelist): Change type of element from `ptr_t` to `void *`.
* misc.c [SEPARATE_GLOBALS] (GC_objfreelist, GC_aobjfreelist,
GC_bytes_allocd): Define variable.